---
- name: Test the website
  hosts: webservers
  become: yes
  become_user: root

  tasks:
  - name: Check Port 80 is listening on manged server
    wait_for:
      port: 80
      state: started
      timeout: 3
  - name: Verify Apcahe is Avilable
    uri:
      url: http://34.201.30.130/index.html
    delegate_to: localhost
  - name: Stat apache2
    stat:
      path: /usr/sbin/apache2
    register: i
  - name: Fail if apache2 does not exist
    assert:
      that:
       - "i.stat.exists"
      fail_msg: " /usr/sbin/apache2 does not exist "
      success_msg: "/usr/sbin/apache2 exists"
      
  - name: verify apache 2 is enabled 
    shell: systemctl list-unit-files | grep apache2.service | awk '{print $2}'
    register: c
  - name: fail if apache 2 is  noy enabled 
    assert:
      that:
       - "c.stdout == 'enabled' "
      fail_msg: " /usr/sbin/apache2 is not enabled "
      success_msg: "/usr/sbin/apache2 is enabled"
  - name: stat index.html
    stat:
      path: /var/www/html/index.html
    register: a
  - name: confirm index.html exist and owned by root
    assert:
      that:
       - "a.stat.exists"
       - "a.stat.pw_name == 'root'"
      fail_msg: " index.html may not exist or not owned by root "
      success_msg: "index.html exist and owned by root"
